spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_service
    username: postgres
    password: Welcome
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    ddl-auto: none
  application:
    name: inventory-service
  profiles:
    active: dev

server:
  port: 8090

KAFKA_BOOSTRAPADDRESS: localhost:9192
GROUPID: order

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${APIMANAGER_SVC_SERVICE_HOST}:${APIMANAGER_SVC_PORT_8000_TCP_PORT}/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true
